### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by kination** [akeating/peap#4]
First, thanks for great sample. I was just planned to going on study with this stack.
After I installed all, I could see the first page but login is not working with `demo@example.com` and `foo`. It keep shows 'please try again'

```
[info] POST /api/token
[debug] Processing by Interface.ApiController.create_token/2
  Parameters: %{"email" => "demo@example.com", "password" => "[FILTERED]"}
  Pipelines: [:api]
[debug] QUERY OK source="users" db=5.4ms
SELECT u0."id", u0."name", u0."email", u0."password_hash", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."email" = $1) ["demo@example.com"]
[info] Sent 401 in 6ms
```
This is the log on terminal. Is there some change on this project?

**Comment by akeating** [comment]
Sorry about that, perhaps I missed something in the recent umbrella refactor. Can you try the following?
```
cd apps/domain
mix ecto.reset
```
Then try to login again.

**Comment by kination** [comment]
@akeating Thanks for quick answer. Now it works! Just one more question.

In apps/, it is separated to domain and interface. I thought it is divided as backend(phoenix) / frontend(angular2). If this is right, why mix.exs and other files for phoenix are exists in interface directory? Is there some other reason, or am I misunderstand something?

Thanks.

**Comment by akeating** [comment]
Ah, well spotted. The `interface` directory contains a phoenix application and the `domain` directory contains a plain `elixir` application. The phoenix application is modified to support everything you should need for developing with angular 2. 

I structured it this way in response to some thoughts shared in various forums. Some references you might take a look at include:
http://www.elixirconf.eu/elixirconf2016/lance-halvorsen (take a look at the video)
https://elixirforum.com/t/phoenix-is-not-your-application-questions/735 (discussion)
https://elixirforum.com/t/how-important-is-the-phoenix-is-not-your-application-mantra/1886
https://confreaks.tv/videos/elixirconf2016-keynote

Essentially, the idea is to separate the interface from the reset of your business logic. Chris McCord also expressed his thoughts about phoenix 1.3 which may change this structure some more when that is released. I kind of like the idea and I will continue to evolve this sample application as my assessment of best practices changes.

**Comment by kination** [comment]
@akeating Thanks! I'll look on it.
